name: openhotel-onet
services:
  web:
    restart: unless-stopped
    container_name: openhotel-onet
    ports:
      - "9400:9400"
    volumes:
      - "openhotel-onet:/app"
    image: "openhotel/onet:latest"
volumes:
  openhotel-onet: null
